// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4doVfgf2XdLT5oVsBC7XG2YvTlbUnT8I',
    appId: '1:662661804756:web:564d2b04d62c563b768141',
    messagingSenderId: '662661804756',
    projectId: 'water-delivery-6ad8f',
    authDomain: 'water-delivery-6ad8f.firebaseapp.com',
    storageBucket: 'water-delivery-6ad8f.appspot.com',
    measurementId: 'G-NBXZ3S43ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_lq-2DfFrq-LLFTxjk5Mm2s92NDq8jgw',
    appId: '1:662661804756:android:b97eb22f86d469fe768141',
    messagingSenderId: '662661804756',
    projectId: 'water-delivery-6ad8f',
    storageBucket: 'water-delivery-6ad8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrt_PFQXCduOwrIlH2d1C7hr7AWt2Gmt4',
    appId: '1:662661804756:ios:a30f4b6b3f80b982768141',
    messagingSenderId: '662661804756',
    projectId: 'water-delivery-6ad8f',
    storageBucket: 'water-delivery-6ad8f.appspot.com',
    iosClientId: '662661804756-be23f2j00u0c76ibo3ajqlg7pi5obd25.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrt_PFQXCduOwrIlH2d1C7hr7AWt2Gmt4',
    appId: '1:662661804756:ios:a30f4b6b3f80b982768141',
    messagingSenderId: '662661804756',
    projectId: 'water-delivery-6ad8f',
    storageBucket: 'water-delivery-6ad8f.appspot.com',
    iosClientId: '662661804756-be23f2j00u0c76ibo3ajqlg7pi5obd25.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterDelivery',
  );
}
